In [11]:
print('Les valeurs sont:\n') #Question1
for x in range(2000,3200) :
    if (x%7)==0 :
        if (x%5!=0) :
            result=[x] 
            print(result)

               
        
    

les valeurs sont:

[2002]
[2009]
[2016]
[2023]
[2037]
[2044]
[2051]
[2058]
[2072]
[2079]
[2086]
[2093]
[2107]
[2114]
[2121]
[2128]
[2142]
[2149]
[2156]
[2163]
[2177]
[2184]
[2191]
[2198]
[2212]
[2219]
[2226]
[2233]
[2247]
[2254]
[2261]
[2268]
[2282]
[2289]
[2296]
[2303]
[2317]
[2324]
[2331]
[2338]
[2352]
[2359]
[2366]
[2373]
[2387]
[2394]
[2401]
[2408]
[2422]
[2429]
[2436]
[2443]
[2457]
[2464]
[2471]
[2478]
[2492]
[2499]
[2506]
[2513]
[2527]
[2534]
[2541]
[2548]
[2562]
[2569]
[2576]
[2583]
[2597]
[2604]
[2611]
[2618]
[2632]
[2639]
[2646]
[2653]
[2667]
[2674]
[2681]
[2688]
[2702]
[2709]
[2716]
[2723]
[2737]
[2744]
[2751]
[2758]
[2772]
[2779]
[2786]
[2793]
[2807]
[2814]
[2821]
[2828]
[2842]
[2849]
[2856]
[2863]
[2877]
[2884]
[2891]
[2898]
[2912]
[2919]
[2926]
[2933]
[2947]
[2954]
[2961]
[2968]
[2982]
[2989]
[2996]
[3003]
[3017]
[3024]
[3031]
[3038]
[3052]
[3059]
[3066]
[3073]
[3087]
[3094]
[3101]
[3108]
[3122]
[3129]
[3136]
[3143]
[3157]
[3164]
[3171]
[3178]
[3192]
[3199]


In [63]:
def facto(x) :#Question2
    fact=1
    for i in range(1,x+1) : 
            fact*=i 
    return fact
        
n=int(input('Veuillez introduir un entier ='))
if n<2 : 
        print('Le factorielle est =',1)
else :
    
    print('\033[94m Le Factorielle de',n,'est =',facto(n))
  

Veuillez introduir un entier =4
 Le Factorielle de 4 est = 24


In [65]:
def dictio(n):       #Question3
    dictio={i:i*i for i in range(1,n+1)}
    return dictio
print('Veuillez introduir un entier n du dictionnaire carré \n')
print('\033[94m Le dictionaire carré de',n,'est=')
n=int(input())
while (type(n)!=str) :
    print(dictio(n))
    break

Veuillez introduir un entier n du dictionnaire carré 

 Le dictionaire carré de 4 est=
4
{1: 1, 2: 4, 3: 9, 4: 16}


In [66]:
def suppcar(car,i):         #Question4
      return car[0:i]+car[i+1:] 
         
car=input('Veuillez saisir votre phrase\n')
print('Veuillez introduir lindex souhaité tel quil soit inférieur a',(len(car)-1))
i=int(input())
if i<(len(car)) :
    print('\033[94m La phrase devient apres supression du',i,'eme caractère : \n')
    print(suppcar(car,i))
else :
    print('\033[91m oups! Veuillez introduire un index adéquant!')

Veuillez saisir votre phrase
je suis la
Veuillez introduir lindex souhaité tel quil soit inférieur a 9
5
 La phrase devient apres supression du 5 eme caractère : 

je sus la


In [68]:
import numpy as np                   #Question5
orig=np.arange(6).reshape(3,2)
print('The Original Array element \n',orig)
toliste=orig.tolist()
print('\033[95m Array to liste\n',toliste)
print(type(toliste))

The Original Array element 
 [[0 1]
 [2 3]
 [4 5]]
 Array to liste
 [[0, 1], [2, 3], [4, 5]]
<class 'list'>


In [70]:
import numpy as np   #Question6
ori1=np.array([[0,1,2],[2,1,0]])
print(ori1)
print('\033[91m La Covariance entre les deux listes  est : \n ')
print(np.cov(ori1))



[[0 1 2]
 [2 1 0]]
 La Covariance entre les deux listes  est : 
 
[[ 1. -1.]
 [-1.  1.]]


In [71]:
C=50                 #Question7
H=30 
x=input('Veuillez saisir les paramètres x de lequation séparés par une virgule :')
list = D.split(',')
import math
print('\033[93m Le resultat est: \n')
for i in  list :
    i=int(i)
    Q=round(math.sqrt((2*C*i)/H))
    valeurs={i:Q} 
    print(valeurs) 


Veuillez saisir les paramètres x de lequation séparés par une virgule :100,150,180
 Le resultat est: 

{100: 18}
{150: 22}
{180: 24}
